stages:
  - build
  - test
  - sonar

before_script:
  - . ci/gitlab-ci-env.sh

.job_template: &job_build
  stage: build
  artifacts:
    expire_in: 42 minutes
    untracked: true
  only:
    - master

.job_template: &job_build_32
  <<: *job_build
  tags:
    - 32bits

.job_template: &job_build_64
  <<: *job_build
  tags:
    - 64bits

build_scotch_32:
  artifacts:
    name: scotch_build_32
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_FILE_COMPRESS_LZMA -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_32

build_scotch_32-d:
  artifacts:
    name: scotch_build_32-d
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_DEBUG_ALL -DSCOTCH_METIS_VERSION=5#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_32

build_scotch_32-dnt:
  artifacts:
    name: scotch_build_32-dnt
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_FILE_COMPRESS_LZMA -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_DEBUG_ALL#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_32

build_scotch_32-dm2:
  artifacts:
    name: scotch_build_32-dm2
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_DEBUG_ALL -DSCOTCH_PTHREAD_NUMBER=2#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_32

build_scotch_32-64d:
  artifacts:
    name: scotch_build_32-64d
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DINTSIZE64 -DIDXSIZE64 -DSCOTCH_DEBUG_ALL#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_32

build_scotch_64:
  artifacts:
    name: scotch_build_64
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_64

build_scotch_64-dm2:
  artifacts:
    name: scotch_build_64-dm2
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_DEBUG_ALL -DSCOTCH_PTHREAD_NUMBER=2#1' Makefile.inc
    - make scotch ptscotch esmumps ptesmumps
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  <<: *job_build_64

build_scotch_64-dr:
  artifacts:
    name: scotch_build_64-dr
  script:
    - cd src
    - cp ../ci/Makefile.inc ./Makefile.inc
    - sed -i -e 's#^\(CFLAGS.*\)#\1 -O0 -g -fPIC -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_DEBUG_ALL -DSCOTCH_RENAME_ALL -DSCOTCH_NAME_SUFFIX=_64#1' Makefile.inc
    - sed -i -e 's#^\(SCOTCH_NAME_SUFFIX.*\)#\1_64#1' Makefile.inc
    - make libscotch libptscotch
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make libscotch libptscotch 2>&1 | tee ../scotch-build.log
  <<: *job_build_64

.job_template: &job_test
  stage: test
  artifacts:
    expire_in: 42 minutes
    paths:
      - scotch-coverage.xml
  script:
    - cd src
    - make check
    - make ptcheck
    - find . -print0 | xargs -0 touch
    - rsync -acv --filter='+ */' --filter='+ *.c' --filter='+ *.h' --filter='+ *.l' --filter='+ *.y' --filter='+ *.gcno' --filter='- *' ./ $GCOV_PREFIX
    - cd $GCOV_PREFIX
    - cp libscotch/parser_ll.c libscotch/lex.yy.c
    - cp libscotch/parser_yy.c libscotch/y.tab.c
    - cd ..
    - lcov --directory $GCOV_PREFIX --capture --output-file scotch.lcov
    - lcov_cobertura.py scotch.lcov --output ../../scotch-coverage.xml
  only:
    - master

.job_template: &job_test_32
  <<: *job_test
  tags:
    - 32bits

.job_template: &job_test_64
  <<: *job_test
  tags:
    - 64bits

test_scotch_32:
  dependencies:
    - build_scotch_32
  artifacts:
    name: scotch_build_32
  <<: *job_test_32

test_scotch_32-d:
  dependencies:
    - build_scotch_32-d
  artifacts:
    name: scotch_build_32-d
  <<: *job_test_32

test_scotch_32-dnt:
  dependencies:
    - build_scotch_32-dnt
  artifacts:
    name: scotch_build_32-dnt
  <<: *job_test_32

test_scotch_32-64d:
  dependencies:
    - build_scotch_32-64d
  artifacts:
    name: scotch_build_32-64d
  <<: *job_test_32

test_scotch_64:
  dependencies:
    - build_scotch_64
  artifacts:
    name: scotch_build_64
  <<: *job_test_64

.job_template: &job_sonar
  stage: sonar
  artifacts:
    expire_in: 1 week
    paths:
      - scotch-coverage.xml
      - scotch-cppcheck.xml
      - scotch-rats.xml
      - sonar-project.properties
      - sonar.log
  script:
    - ci/analysis.sh
    - sonar-scanner -X > sonar.log
  only:
    - master

sonar_scotch_32:
  dependencies:
    - build_scotch_32
    - test_scotch_32
  artifacts:
    name: scotch_build_32
  tags:
    - 32bits
  <<: *job_sonar

sonar_scotch_64:
  dependencies:
    - build_scotch_64
    - test_scotch_64
  artifacts:
    name: scotch_build_64
  tags:
    - 64bits
  <<: *job_sonar
