image: hpclib/hiepacs

stages:
  - build
  - test
  - sonar

before_script:
  - git submodule update --init --recursive
  - source .gitlab-ci-env.sh
  - . /etc/profile.d/spack.sh

build_scotch:
  stage: build
  artifacts:
    name: scotch_build
    expire_in: 42 minutes
    untracked: true
  script:
    - cd src
    - cp ./Make.inc/Makefile.inc.x86-64_pc_linux2 ./Makefile.inc
    - sed -i -e "s#^CFLAGS.*#CFLAGS = -O0 -g -fPIC --coverage -Wall -fdiagnostics-show-option `pkg-config --cflags ompi-c` -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -DSCOTCH_PTHREAD -Drestrict=__restrict -DIDXSIZE64#g" Makefile.inc
    - sed -i -e "s#^LDFLAGS.*#LDFLAGS = --coverage `pkg-config --libs --static ompi-c` -lz -lm -lrt -pthread#g" Makefile.inc
    - scan-build -plist --intercept-first --analyze-headers -o ../analyzer_reports make scotch ptscotch esmumps ptesmumps 2>&1 | tee ../scotch-build.log
  only:
    - branches
    - master@scotch/scotch

test_scotch:
  stage: test
  dependencies:
    - build_scotch
  artifacts:
    name: scotch_build
    expire_in: 42 minutes
    paths:
      - scotch-coverage.xml
  script:
    - cd src
    - make -j 4 check
    - make -j 4 ptcheck
    - find . -print0 | xargs -0 touch
    - rsync -acv --filter='+ */' --filter='+ *.c' --filter='+ *.h' --filter='+ *.l' --filter='+ *.y' --filter='+ *.gcno' --filter='- *' ./ $GCOV_PREFIX
    - cd $GCOV_PREFIX
    - cp libscotch/parser_ll.c libscotch/lex.yy.c
    - cp libscotch/parser_yy.c libscotch/y.tab.c
    - cd ..
    - lcov --directory $GCOV_PREFIX --capture --output-file scotch.lcov
    - lcov_cobertura.py scotch.lcov --output ../../scotch-coverage.xml
  only:
    - branches
    - master@scotch/scotch

sonar_scotch:
  stage: sonar
  dependencies:
    - build_scotch
    - test_scotch
  artifacts:
    name: scotch_sonar
    expire_in: 1 week
    paths:
      - scotch-coverage.xml
      - scotch-cppcheck.xml
      - scotch-rats.xml
      - sonar-project.properties
      - sonar.log
  script:
    - ./analysis.sh
    - sonar-scanner -X > sonar.log
  only:
    - master@scotch/scotch
